return {
  WagstaffMod={
    configuration_options={
      debug=true,
      enableblur=true,
      flickerthreshold=0.75,
      gogglesrestricted=false,
      language="auto",
      mysterychance=0.03,
      mysterymidchance=0.7,
      mysterynilchance=0.4,
      preset="NONE",
      telebrellarandom=true,
      telebrellaspelltype="item",
      weakstomachpain=-3 
    },
    enabled=true 
  } 
}